@echo off
echo Attempting to kill any process on port 8080...
for /f "tokens=5" %%a in ('netstat -ano ^| findstr :8080 ^| findstr LISTENING') do (
    echo Found process with PID: %%a. Killing it now...
    taskkill /f /pid %%a
)
echo Starting Spring Boot application...
mvn spring-boot:run